#!/usr/bin/expect -f

set ip "10.2.143.213"
set hostname [lindex $argv 0]
set username "root"
set password "changeme"

spawn ssh -o StrictHostKeyChecking=no $username\@$hostname

expect {
timeout { send_user "\nTimeout Exceeded - Check Host\n"; exit 1 }
eof { send_user "\vnSSH Connection To $hostname Failed\n";
        spawn telnet $hostname
        expect {
        timeout { send_user "\nTelnet failed Timeout\n"; exit 1 } 
        eof { send_user "\nTelnet Connection failed\n"; exit 1 } 
	default { send_user "\nTelnet login failed check user\n"; exit 1 }
        "*#" {}
        "*assword:" {
        send "$password\n"
        }
	"*sername:" {
	send "$username\n"
	expect {
		"*#" {}
		"*assword:" {
		send "$password\n"
		}
	}
        }
	}
}
"*#" {}
"*assword:" {
send "$password\n"
}
}

expect {
default { send_user "\nEnable Mode Failed - Check Password\n"; exit 1 }
"*#" {}
"*>" {
send "enable\n"
expect "*#"
}
}

send "tclsh tftp://$ip/deploy2.tcl\n"
expect "*#"
send "copy running-config startup-config\n"
expect "*#"
exit
